### ISSUE TITLE
Occasionally missing _stripe_net, _stripe_fee, and _stripe_currency meta

### ISSUE THREAD

**Issue by danieleperilli** [woocommerce/woocommerce-gateway-stripe#2478]
We noticed that **sometimes** the following attributes are not stored in completed orders (paid with CC): 
- _stripe_net
- _stripe_fee
- _stripe_currency 

No errors are logged and the other data is present. It doesn't happen for every order but occasionally, although in recent weeks it's more frequent.

As we use a plugin for Quickbooks that needs these attributes, we need to make sure that data is always available.
Do you know why this happens? Do you have any advice, or some code  to retrieve this information in a batch later or something similar?

Thanks!

**Environment:**
 - WordPress 6.1
 - WooCommerce 7.0.1
 - Stripe Plugin 6.9.0

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

> As we use a plugin for Quickbooks that needs these attributes, we need to make sure that data is always available.
Do you know why this happens?

I can't find any other similar reports so I wonder if this is a conflict. I appreciate some time has passed since the original comment, thanks for your patience - have you made any progress to understanding the cause of this? 

To confirm if this is a bug or conflict, please first go through the WooCommerce [How to Test for Plugin and Theme Conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/) documentation.

**Comment by danieleperilli** [comment]
I do confirm that the issue still exists, but as I said, it's not programmatic, so I cannot just disable all the other plugins to see if it still occurs. This is something sporadic, and we are handling with a custom hook that is triggered when an order is completed, checking if those metas are missing and, if so, sending us an email.

**Comment by grig-23** [comment]
Not sure if it's the same issue as described here - but with the latest version of Stripe, 8.6.1, if "Issue an authorization on checkout, and capture later" checkbox in the settings is un-ticked - the Stripe fee and Stripe Payout will be missing:
<img width="1090" alt="Screenshot 2024-08-13 at 19 25 02" src="https://github.com/user-attachments/assets/4612d119-95a9-418e-b2cb-42d1053f3d75">

This is how it's supposed to look like:

<img width="564" alt="Screenshot 2024-08-13 at 19 25 28" src="https://github.com/user-attachments/assets/2f4e3ec7-63d2-4e39-bbba-9b9d066bbcf6">

I was able to replicate on a test site.

**Comment by mattallan** [comment]
This one might've been fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3508 cc @wjrosa as I see you're assigned to this :)

**Comment by wjrosa** [comment]
Hi @danieleperilli ! Can you confirm if the issue has been solved for you? The update above is available since [version 8.8.0](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/8.8.0). We are currently in 8.8.1.

**Comment by danieleperilli** [comment]
@wjrosa No, v8.8.1 didn't solve the problem. I tested v8.8.0 and v8.8.1 and both have this problem. I downgraded to 8.7.0 and the double hooks disappeared.

**Comment by danieleperilli** [comment]
I can't test it unfortunately, because v8.8.0 and v8.8.1 have another issue with double order processing. I will test it when a fix will be available for the other problem. Ref: #3501

**Comment by danieleperilli** [comment]
I confirm we didn't receive the error again. I will reopen the issue in case it occurs again. Thanks for you support!
