### ISSUE TITLE
Stripe Link button do not disappear even if it is disabled

### ISSUE THREAD

**Issue by thisissandip** [woocommerce/woocommerce-gateway-stripe#2479]
**Describe the bug**
The ‘Link pay Faster’ button does not disappear even if it disabled from Stripe > Express Checkout settings

**To Reproduce**
1. Enable Stripe Link from WooCommerce > Settings > Payments > Stripe > Express Checkout 
2. Go to the cart page -> See the "Stripe Link" button
3. Now, disable Stripe Link Express checkout 
4. See the button does not disappear

**Expected behavior**

The button should disappear if the Stripe Link option is disabled

**Screenshots**

![BozQ27.gif](https://user-images.githubusercontent.com/69596988/202177718-64449201-c930-476c-87b8-04817e456c90.gif)

**Workaround**

The only way to remove the Stripe Link button is to disable it from the Stripe dashboard itself: https://dashboard.stripe.com/settings/link

![x1Hzpp.png](https://user-images.githubusercontent.com/69596988/202175966-a0ab7a2b-6921-4594-a5fb-853ef69b3aaf.png)

**Comment by thisissandip** [comment]
Reported here: https://wordpress.org/support/topic/disabling-link-by-stripe/page/2/

**Comment by glagonikas** [comment]
Just to follow up on this, on a UK store, there's no option to disable Link from WC admin.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/10516403/202219508-78c8e81d-f1e1-40f4-979f-f05d320baf17.png">

**Comment by gofreem** [comment]
Just to help follow up on this, on a DE store, there's also no option to disable Link from WC admin.
But the workaround above, help me to solve the problem :-)
Thanks

![2022-11-16_00-51-41](https://user-images.githubusercontent.com/106705909/202269535-4e16238c-ee50-496f-ac8f-220716046790.png)

**Comment by jvwrx** [comment]
_EDIT: The 'workaround' works for me too and Link no longer appears when I disable it at https://dashboard.stripe.com/settings/link_

Happening for me too:

- Link is **off** at Stripe itself https://dashboard.stripe.com/settings/payment_methods
- Within _Woo > Settings > Payments > Stripe > Express Checkouts_: Link is not an option (only Apple/Google Pay)
- Link still appears when viewing in Chrome on Mac (and Chrome on Windows via Browserling). Apple Pay appears there when using Safari.

See screenshots + system report attached. Was able to get a reduced test case of sorts on our staging server and currently have:

- WP 6.1.1
- Storefront theme 4.2.0
- Only active plugins are WooCommerce (7.1.0)  + WooCommerce Stripe Gateway (7.0.1)

![LinkIssue-1-Stripe](https://user-images.githubusercontent.com/233177/202280329-d8af3609-c0f8-4740-bc9d-0396a0cba7bc.jpg)
![LinkIssue-2-Woo](https://user-images.githubusercontent.com/233177/202280338-4592b31f-b3fa-4e84-bdef-86b8860c8c2f.jpg)
![LinkIssue-3](https://user-images.githubusercontent.com/233177/202280343-ff438e6f-13e8-4be5-bd0c-b5236a71f0ce.jpg)

**Comment by gofreem** [comment]
> https://dashboard.stripe.com/settings/link

This is not the right place to deactivate it.
You have to go to https://dashboard.stripe.com/settings/link

Maybe it helps you ;-)

**Comment by jvwrx** [comment]
@gofreem INDEED. Thank you!

https://dashboard.stripe.com/settings/payment_methods was actually my original link. Disabled it at https://dashboard.stripe.com/settings/link and Link no longer appears.

Hopefully that'll solve it for others as well. Maybe this plugin could display that link within settings.

(I'll be sure to file a feature request with Stripe devs too to maybe link to that page from the one I posted 😄)

**Comment by thisissandip** [comment]
5715294-zen

**Comment by fetenlakhal** [comment]
5715288-zd

**Comment by kaushikasomaiya** [comment]
5711594-zen

**Comment by neilmccreadie** [comment]
5740500-zen

**Comment by rossviviano** [comment]
38320347- hc

**Comment by Brianmitchtay** [comment]
Just had a user from the UK in 38303815-hc where the workarounds mentioned here didn't work.

On their site, they're still seeing the `Stripe Link` button as the only express checkout option, despite having de-activated Stripe link at [https://dashboard.stripe.com/settings/link](https://dashboard.stripe.com/settings/link), and also at [https://dashboard.stripe.com/settings/payment\_methods](https://dashboard.stripe.com/settings/payment_methods)

Not sure where to take this from here with it still showing after being disabled in the Stripe dash, I've asked for logs in a followup to see what clues may lie there.

**Comment by davinian** [comment]
Same problem with another UK website (going to check all UK sites I manage). The option in "Express Checkout" is not visible, so had to disable in Stripe.

The big question I have is, how did "Link" get turned on in the first place? Did Stripe do this or was it something the "WooCommerce Stripe Payment Gateway" plugin enabled?

**Comment by amber-c** [comment]
Happening for me too for CA sites:

- Link is deactivated in Stripe itself: [](https://dashboard.stripe.com/settings/link)
- Within Woo > Settings > Payments > Stripe > Express Checkouts: Link is not an option (only Apple/Google Pay)
- Link still appears when viewing in Chrome

**Comment by ccollabgist** [comment]
Happening for us too for CA sites:

- Link is deactivated in Stripe itself: [https://dashboard.stripe.com/settings/link](https://dashboard.stripe.com/settings/link)
- Within Woo > Settings > Payments > Stripe > Express Checkouts: Link is not an option (only Apple/Google Pay)
- Link still appears when viewing in Chrome

**Comment by paulostp** [comment]
5789117-zen

**Comment by jacoswan** [comment]
5784973-zen

It seems like once activated, Stripe Link button is offered wherever Google/Apple Pay is not configured in the browser. Disabling the setting seems problematic (even in the Stripe account), as the button persists across browsers and devices until Express Checkout is disabled (but continues when enabled).

**Comment by lynnjat7** [comment]
5783352-zen

**Comment by rossviviano** [comment]
5824971-zen

**Comment by csmcneill** [comment]
39488129-hc

What I've found in my personal experience is that Stripe Link will load if EPMs are enabled but Google/Apple Pay won't load for the customer.

**Comment by supton71** [comment]
> Just had a user from the UK in 38303815-hc where the workarounds mentioned here didn't work.
> 
> On their site, they're still seeing the `Stripe Link` button as the only express checkout option, despite having de-activated Stripe link at https://dashboard.stripe.com/settings/link, and also at https://dashboard.stripe.com/settings/payment_methods
> 
> Not sure where to take this from here with it still showing after being disabled in the Stripe dash, I've asked for logs in a followup to see what clues may lie there.

I have the same issue.  I am UK based, I have disabled Link in my Stripe account on the two pages as recommended but it still shows up.  Interestingly, I got so annoyed I disabled and deleted WooCommerce payments plugin, and installed Stripe's own plugin instead - exactly the same issue.  the only way I can get the damn thing to go away is to disable Google and Apply pay altogether.

**Comment by ausworkshop** [comment]
I'm trying to figure this out also.  I don't think anyone in Australia even uses Link so I want it to go away rather than confuse potential buyers.  This is so annoying. I ended up clicking through after reading the note at the top of the page and it took me here to this page.  I'm a bit overwhelmed at this point.  
https://stripe.com/docs/payments/payment-element/migration#one-time-payment-intent 

I may have to pay someone to figure all this out.  We shouldn't have to though. We pay enough money to these payment processors.  Why can't they just make things simple for us?

**Comment by tsetend** [comment]
Another report: 6043874-zen

**Comment by marissaexplores** [comment]
[6044535-zen](6044535-zd-woothemes)

**Comment by avantegarde** [comment]
6037204-zen

**Comment by stoltzrx** [comment]
6216178-zen

**Comment by masteradhoc** [comment]
+1 please get this fixed

**Comment by jacoswan** [comment]
6239942-zen

**Comment by skullo27** [comment]
We are in the UK, no one has ever heard of Link here so will be negatively impacting conversions, especially because on our site, if the customer is not logged in (even if google/apple pay is configured in the browser) they get served the Link button.

If I disable in stripe as suggested here, then it disables the google and apple pay buttons as well.

It's crazy that this seems to remain unfixed since November as all the devs need to do is allow the Link settings in the stripe plugin for countries outside the US.

Come on guys, we don't see this kind of issue in Shopify!!!

**Comment by gbtim** [comment]
We experienced a similar issue but learned, at least for us, the answer was in "Test Mode" vs. "Live".

For WooCommerce, the Stripe mode is set here:  Woo > Settings > Payments > Stripe > Settings.  The "Enable test mode" checkbox is in the "General" settings.  You want to be sure you're adjusting settings at Stripe in the environment that matches your website.

In the Stripe interface, there is a "Test mode" toggle in the top-right corner.

We had our website in test mode and Stripe by default is in the "live" mode when you login.  If you toggle off the Link settings (https://dashboard.stripe.com/settings/link)  it does not stop the website in test mode from putting out the "Link pay faster" button.  You must also toggle Stripe to "test mode" and disable link again.

**Comment by jackfaulkner** [comment]
Maybe the Stripe team made some changes recently; I was able to disable the Link button by turning off the "Link for Payment Request Button" in the Stripe Dashboard, even in Test Mode. I'm in Australia and my WooCommerce settings page does not have the Link option under Payments, so I couldn't turn it off there.

**Comment by SteStory** [comment]
Had same issue here, UK based store and UK based computer, but for some reason on desktop it would show Pay By Link, but mobile worked fine showing apple pay/google pay.

Managed to go to https://dashboard.stripe.com/settings/link and disable link pay there, which removed the link pay button on desktop, but now there's no express checkout showing atall on desktop.

Link: http://thelakesfabricstore.co.uk

**Comment by BoyetDgte** [comment]
> Happening for us too for CA sites:
> 
> * Link is deactivated in Stripe itself: https://dashboard.stripe.com/settings/link
> * Within Woo > Settings > Payments > Stripe > Express Checkouts: Link is not an option (only Apple/Google Pay)
> * Link still appears when viewing in Chrome

Same for me (CA site)

**Comment by xue28** [comment]
6326754-zen

**Comment by dreamtooloud** [comment]
6354610-zen

**Comment by tomahhunt** [comment]
So glad this has been fixed and merged to develop. When would we expect a plugin update we can deploy?

**Comment by cremigerhonig** [comment]
its still an issue in Germany. please see here

![Image](https://github.com/user-attachments/assets/7f4eda0d-d4e6-4e36-a035-f15838a46567)
also here

![Image](https://github.com/user-attachments/assets/716f7110-f9cb-4a94-8601-423c44e2cb39)

I try to remove it using CSS like this

```
.p-LinkAutofillPrompt {
  display: none!important;
}
```

and

```
.AnimateSinglePresenceItem.p-LinkAutofillPrompt-animationItem {
  display: none;
}
```

no changes

I also turn of under 

https://dashboard.stripe.com/settings/link
no changes
I also try to turn of under
https://dashboard.stripe.com/settings/payment_methods

but stripe keeps telling me that woocomerce (the payment plugin) is handling the payments so I cant do anything..

what to do?

**Comment by cremigerhonig** [comment]
I just noticed 

when I have stripe gateway as second payment option while using the customizer to block css

```
.p-LinkAutofillPrompt {
  display: none!important;
}
```
then the link text is not display

the reason is that stripe is loading the link text with a little delay. try it yourself

**Comment by vishalnagv** [comment]
I have posted the solution in [here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2880#issuecomment-2670519161). Hope this will work. Cheers

**Comment by cremigerhonig** [comment]
no its not working. I disabled link all over stripe dashboard, in test mode and live mode.
https://imgur.com/iPmdC0E

stripe is telling me its handled by checkout plugin.
see here: https://wordpress.org/support/topic/link-advertising-during-payment/#post-18322996

but checkout plugin does not have any settings regarding link

**Comment by Mayisha** [comment]
Hi @cremigerhonig 👋 

The Stripe payment element in the screenshot you shared in your [first comment](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2479#issuecomment-2628831945) is not from our plugin (WooCommerce Stripe Payment Gateway). I have checked and confirmed that in this plugin, the Link form appears below the credit/debit card element only when Link is enabled in the settings.
