### ISSUE TITLE
Version 7.9.2 does not allow payments / checkouts if Customer Order Number added to Bank Statement

### ISSUE THREAD

**Issue by lynnjat7** [woocommerce/woocommerce-gateway-stripe#2885]
**Describe the bug**
With Stripe version 7.9.2 running, if the option to "Add customer order number to the bank statement" is active /checked in the Stripe settings, then on every attempted checkout, there's an error:
`Sorry, we are unable to process your payment at this time. Please retry later.`

Internal ref: 7712089-zen

In the log files, we can see this error:

```
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [message] => The statement descriptor must contain at least one Latin character.
            [param] => statement_descriptor_suffix
            [request_log_url] => https://dashboard.stripe.com/test/logs/req_ZnRpvf0KheCxiB?t=100000
            [type] => invalid_request_error
        )

)
```

Looks like the statement descriptor is only picking up the order number, not the prefix:

```
[payment_method] => pm_XXXX
    [customer] => cus_XXXX
    [statement_descriptor_suffix] => #96054
    [shipping] => Array
```

Note that the Full Bank Statement descriptor is only 8 characters, so no Shortened Descriptor is entered as it should not be required.

**To Reproduce**
1. Install Stripe version 7.9.2
2. Go to WooCommerce > Settings on the "Payments" tab
3. Click "Manage" next to Stripe and enter a Full Bank Statement descriptor that is fairly short, and check the option to "Add customer order number to the bank statement"
4. Enable logging too while you're here, it's okay to set Stripe to test mode too
5. attempt a checkout with Stripe - see the error on the checkout page "Sorry, we are unable to process your payment at this time. Please retry later."

**Expected behavior**
Rolling back to version 7.9.1 worked for the original reporting customer so something has changed between these two versions - I do see in the release notes that this section of the code was directly changed with version 7.9.2. 

**Screenshots**
Stripe settings:

![A7oz0W.png](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/109691691/60b1f177-5af1-4626-b2c9-bb14fdb74004)

**Environment (please complete the following information):**
I was able to duplicate this on my test site, here is its SSR:

```
### WordPress Environment ###

WordPress address (URL): https://numbertwo.mystagingwebsite.com
Site address (URL): https://numbertwo.mystagingwebsite.com
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.2.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.4.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: wp_
Total Database Size: 62.91MB
Database Data Size: 38.36MB
Database Index Size: 24.55MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 13.14MB + Index: 11.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.11MB + Index: 5.06MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_em_bookings: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_em_bookings_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_em_events: Data: 0.02MB + Index: 0.16MB + Engine InnoDB
wp_em_locations: Data: 0.02MB + Index: 0.20MB + Engine InnoDB
wp_em_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_em_tickets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_em_tickets_bookings: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_em_tickets_bookings_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.17MB + Index: 0.20MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 5.52MB + Index: 1.98MB + Engine InnoDB
wp_posts: Data: 0.28MB + Index: 0.19MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcrp_rental_products_rentals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcrp_rental_products_rentals_archive: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deploymentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_prl_deployments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_prl_frequencies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_generator_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_prl_tracking_conversions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

afreg_fields: 1
attachment: 89
aw_workflow: 1
bookable_person: 3
bookable_resource: 16
def_reg_fields: 10
event: 1
event_ticket: 4
follow_up_email: 1
mail-debug: 274
mailpoet_page: 1
nav_menu_item: 9
page: 17
post: 1
po_product_options: 4
prl_engine: 4
product: 83
product_variation: 40
revision: 18
shop_bogof_rule: 1
shop_coupon: 7
shop_order: 123
shop_order_refund: 8
shop_subscription: 9
wc_booking: 37
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.1
Code Snippets: by Code Snippets Pro – 3.6.2
Jetpack: by Automattic – 13.1.1
Loco Translate: by Tim Whitlock – 2.6.6
Mail Debug for WooCommerce: by Leanza Francesco – 1.3.0
MailPoet: by MailPoet – 4.43.0
Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce Bookings Availability: by WooCommerce – 1.2.4
WooCommerce Bookings: by WooCommerce – 2.0.9
WooCommerce Stripe Gateway: by WooCommerce – 7.9.2
Woo Min/Max Quantities: by Woo – 4.1.4
WooCommerce PayPal Payments: by WooCommerce – 2.5.3
WooCommerce: by Automattic – 8.5.2
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Mail SMTP: by WP Mail SMTP – 3.11.1

### Inactive Plugins (41) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.2
AutomateWoo: by WooCommerce – 6.0.10 (update to version 6.0.15 is available)
Avalara AvaTax: by Avalara – 2.5.0 (update to version 2.7.0 is available)
Bookings Helper: by WooCommerce – 1.0.3
Currency per Product for WooCommerce: by Tyche Softwares – 1.6.0
Custom User Registration Fields for WooCommerce: by Addify – 2.0.0 (update to version 2.1.1 is available)
Events Manager: by Pixelite – 6.4.6.1
Events Manager for WooCommerce: by Pixelite SL – 0.13
Mailchimp for WooCommerce: by Mailchimp – 3.2
Order Export & Order Import for WooCommerce: by WebToffee – 2.4.0
Price by Formula Calculator for WooCommerce: by Plugify – 3.0.1 (update to version 3.0.6 is available)
Product Import Export for WooCommerce: by WebToffee – 2.3.5
Rental Products: by 99w – 4.3.3 (update to version 4.4.2 is available)
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Variation Price Display Range for WooCommerce: by WPXtension – 1.3.10
WooCommerce Accommodation Bookings: by WooCommerce – 1.2.2 (update to version 1.2.4 is available)
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.10 (update to version 1.1.11 is available)
WooCommerce Box Office: by WooCommerce – 1.2.2 (update to version 1.2.4 is available)
WooCommerce Buy One Get One Free: by Oscar Gare – 4.0.4 (update to version 4.1.5 is available)
WooCommerce Conditional Shipping and Payments: by WooCommerce – 1.15.2 (update to version 1.15.5 is available)
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.11.0 (update to version 3.12.0 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.4.1 (update to version 5.5.0 is available)
WooCommerce Deposits: by WooCommerce – 2.2.0 (update to version 2.2.5 is available)
WooCommerce Distance Rate Shipping: by WooCommerce – 1.3.4 (update to version 1.4.0 is available)
WooCommerce Gift Cards: by WooCommerce – 1.16.5 (update to version 1.16.9 is available)
WooCommerce One Page Checkout: by Automattic – 2.3.0 (update to version 2.8.1 is available)
WooCommerce PDF Watermark: by WooCommerce – 1.5.1 (update to version 1.6.3 is available)
WooCommerce Pre-Orders: by WooCommerce – 2.0.7 (update to version 2.0.9 is available)
WooCommerce Product Bundles: by WooCommerce – 6.22.5 (update to version 6.22.6 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.57 (update to version 1.10.68 is available)
WooCommerce Product Recommendations: by WooCommerce – 3.0.4 (update to version 3.0.6 is available)
WooCommerce Royal Mail: by WooCommerce – 2.7.0 (update to version 3.2.0 is available)
WooCommerce Shipment Tracking: by WooCommerce – 2.3.2 (update to version 2.4.4 is available)
WooCommerce Shipping & Tax: by WooCommerce – 2.4.0 (update to version 2.4.2 is available)
WooCommerce Smart Coupons: by StoreApps – 8.4.0 (update to version 8.16.0 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.1.2 (update to version 3.1.6 is available)
Woo Product Add-ons: by Woo – 6.5.2 (update to version 6.6.0 is available)
Woo Subscriptions: by WooCommerce – 5.8.0 (update to version 6.0.0 is available)
WP All Import: by Soflyy – 3.7.3
WP All Import - WooCommerce Add-On: by Soflyy – 1.5.1
WPForms Lite: by WPForms – 1.8.5.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0 (update to version 4.5.4 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-08 18:59:03 -05:00
Options: ✔
Notes: 156
Onboarding: skipped

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Default WordPress sending method
Task Scheduler method: Action Scheduler
Cron ping URL: https://numbertwo.mystagingwebsite.com?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Complete: 22,344
Oldest: 2024-01-08 12:58:58 -0500
Newest: 2024-02-08 12:58:16 -0500

Failed: 275
Oldest: 2023-01-19 14:14:14 -0500
Newest: 2023-12-22 12:49:32 -0500

Pending: 12
Oldest: 2024-02-08 13:00:16 -0500
Newest: 2024-10-02 13:53:51 -0400


### Status report information ###

Generated at: 2024-02-08 12:58:41 -05:00
```

**Comment by hitsgee** [comment]
I have experienced the same issue since update. Rolled back until a fix is released.

**Comment by Snaacks** [comment]
Also present in ZD-7711828, rolling back Stripe resolved for now.

**Comment by yukikatayama** [comment]
7717743-zd also reported this. Offered rollback as an option but they decided to disabling the "Order number on the bank statement" option for now, which also works as a workaround.

**Comment by shaunkuschel** [comment]
Another report on 7712286-zen. Shared workaround involving disabling that option in the settings.

**Comment by carolframen** [comment]
7717989-zen.

**Comment by battouly** [comment]
7720919-zen. Unchecking the "Add customer order number to the bank statement" box fixed it for now.

**Comment by battouly** [comment]
7712771-zen. Suggested unchecking the "Add customer order number to the bank statement".

**Comment by theabhig** [comment]
Also in 7722177-zd-a8c

**Comment by doublezed2** [comment]
7712897-zen
Suggested unchecking the "Add customer order number to the bank statement".

**Comment by raifd** [comment]
Also reported here: 7723397-zen

**Comment by grig-23** [comment]
7722171-zen

**Comment by Brianmitchtay** [comment]
7725250-zen
7725217-zen
7725657-zen

**Comment by Brianmitchtay** [comment]
I labeled this as critical. Feel free to re-prioritize as you see fit, but we should not have merchants who are having every transaction fail because they updated to the latest version. Needs an urgent fix IMO.

**Comment by theabhig** [comment]
7710053-zd-a8c

**Comment by anastas10s-afk** [comment]
7726285-zen

**Comment by Brianmitchtay** [comment]
7728853-zd-a8c

**Comment by Brianmitchtay** [comment]
7729132-zd-a8c

**Comment by a-danae** [comment]
This issue should have been fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2890, which is already included in the latest release of Stripe: [7.9.3](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/7.9.3)

**Comment by fetenlakhal** [comment]
@a-danae 7743570-zd told me they had updated the plugin but were still seeing the same error.

**Comment by Mayisha** [comment]
@fetenlakhal I see that you have already requested for the logs. Let's see what we find there. :eyes:

**Comment by wyter** [comment]
7769308-zen, they reported they'd been experiencing the same error. Their SSR was reading Stripe version 7.9.3, so I'm confirming whether this error persisted even after updating to 7.9.3.

**Comment by wyter** [comment]
@Mayisha regarding 7769308-zen, the merchant has confirmed they are using Stripe version 7.9.3 but the error persists.

**Comment by sukafia** [comment]
7794507-zen v7.9.3

**Comment by Mayisha** [comment]
Hi @lynnjat7 :wave: 
Do you mind sharing your test account where you could reproduce the issue?

**Comment by lynnjat7** [comment]
@Mayisha It's this site --> https://numbertwo.mystagingwebsite.com
The SSR in the original report above is from that site. It's still set up with Stripe 7.9.2, please let me know if you'd like me to upgrade. The setting to include order number is active at the moment.

If you'd like access to it for testing please message me on Slack, I'd be happy to let you use it.

**Comment by Mayisha** [comment]
Another fix PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2961 is merged and it will be shipped in `8.0.0` this week.

**Comment by BrightAntie** [comment]
Good morning. What should i write in the full bank statement? Thank you

**Comment by Mayisha** [comment]
@BrightAntie you can not add the full bank statement from the Stripe settings page. It's a readonly field now. However, you may add/change this in your Stripe dashboard. You can find the following instructions in your Stripe settings page about the statement descriptor.

> You can change the description your customers will see on their bank statement in your [Stripe account settings](https://dashboard.stripe.com/settings/public). Set this to a recognizable name – e.g. the legal entity name or website address – to avoid potential disputes and chargebacks.
