### ISSUE TITLE
Invalid IP address with the new checkout

### ISSUE THREAD

**Issue by mohitgusain** [woocommerce/woocommerce-gateway-stripe#3543]
**Describe the bug**<br>With the new Stripe checkout, users are encountering an "Invalid IP address" error. The specific error message is: "Payment failed: Invalid IP address. Order status changed from Pending payment to Failed." This issue does not occur with the legacy checkout

**To Reproduce**<br>This issue is affecting many users, and a [thread](<https://wordpress.org/support/topic/no-ip-address-supplied/#post-18093119>) has already been started regarding it. However, no one has been able to find a solution yet

Adding another [topic](<https://wordpress.org/support/topic/payment-failed-invalid-ip-address-with-the-new-stripe-checkout/#new-topic-0>)

**Expected behavior**<br>With the new checkout, this error should not come.

**Environment (please complete the following information):**

* WordPress Version - 6.2.2
* WooCommerce Version - 8.8.5
* Stripe Plugin Version - 8.7.0
* On every browser

**Comment by annemirasol** [comment]
See https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3554 (closed as duplicate) for a similar case, reported in WC Community Slack.

Additional details that may be relevant:
- This is for Subscriptions orders, which require mandate data to be sent with the payment intent.
- The payment intent object has this error on the Stripe dashboard: `Invalid_request_error - mandate_data[customer_acceptance][online][ip_address]`
   - `WC_Geolocation::get_ip_address()` must be returning an empty string for this to happen.
   - Server variables `HTTP_X_REAL_IP`, `HTTP_X_FORWARDED_FOR`, `REMOTE_ADDR` must all be empty for `WC_Geolocation::get_ip_address()` to return an empty string.

**Comment by annemirasol** [comment]
The merchant in #3554 returned with this:

```
in Load balancer on EC2, there's a "Client port preservation" option, which sends the address, in our case, HTTP_X_FORWARDED_FOR in IP_ADDRESS:PORT format, which get_ip_address fails to recognise and returns the empty string.
```

I will look at filing a WooCommerce issue to request support for the `IP_ADDRESS:PORT` format.

@mohitgusain Is your prod server perhaps using the same setup?

**Comment by annemirasol** [comment]
Merchant in #3554 has confirmed that turning off "Client port preservation" fixes the issue.

I have filed https://github.com/woocommerce/woocommerce/issues/52390, requesting to add support in `WC_Geolocation::get_ip_address()` for said XFF format.

**Comment by annemirasol** [comment]
This has been [fixed in core](https://github.com/woocommerce/woocommerce/pull/52551), to be included in the 9.6.0 release.

**Comment by limist** [comment]
@annemirasol We're still seeing this problem after upgrading to latest WordPress, WooCommerce, and Stripe plugin (versions 6.7.1, 9.6.1, and 9.1.1 respectively). Stripe log shows an empty string "" being sent by WooCommerce as the IP number, which Stripe rejects with error message "Invalid IP number"

**Comment by annemirasol** [comment]
Re-opening this issue.

@limist Do you have the same setup as https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3543#issuecomment-2442415027?

Also, is this happening for all transactions? Are you able to install the Code Snippets plugin? I'd like to see what `WC_Geolocation::get_ip_address()`, `$_SERVER['HTTP_X_REAL_IP']`, `$_SERVER['HTTP_X_FORWARDED_FOR']` and `$_SERVER['REMOTE_ADDR']` are returning.

**Comment by raifd** [comment]
9384411-zen is also still experiencing the issue with all the latest plugins, we, however, cannot replicate the issue on staging which is weird.

**Comment by grig-23** [comment]
9384411-zd-a8c - I turned the following question:

> I'd like to see what WC_Geolocation::get_ip_address(), $_SERVER['HTTP_X_REAL_IP'], $_SERVER['HTTP_X_FORWARDED_FOR'] and $_SERVER['REMOTE_ADDR'] are returning.

into a [code snippet](https://gist.github.com/grig-23/e2769f58104e04104524c0428e0d2e42)/plugin and provided that to the merchant so we can get some logs. We'll share the results here once we have them.

**Comment by limist** [comment]
@annemirasol Thanks for your speedy reply!

> [@limist](https://github.com/limist) Do you have the same setup as [#3543 (comment)](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3543#issuecomment-2442415027)?
> 

No, our webhost is using a dedicated VM on Google's Cloud.

> Also, is this happening for all transactions? 

No, not all Stripe credit card transactions are seeing this problem, only some.  And when the order/checkout fails, it's always with a Stripe credit card transaction.  PayPal and Stripe Link work fine.

> Are you able to install the Code Snippets plugin? I'd like to see what `WC_Geolocation::get_ip_address()`, `$_SERVER['HTTP_X_REAL_IP']`, `$_SERVER['HTTP_X_FORWARDED_FOR']` and `$_SERVER['REMOTE_ADDR']` are returning.

I'll look into capturing/logging that info when an order fails with `Invalid IP`, thanks for the pointer.

**Comment by ethanclevenger91** [comment]
To add another data point, I have a client experiencing this issue. We've enabled "legacy" mode in the meantime and I'll update my comment if for some reason that doesn't fix it. The site is hosted on Kinsta.

**Comment by andreliem** [comment]
@ethanclevenger91 I also have a client hosted on Kinsta that is experiencing the same issue, and for now have opted in for Legacy mode until we can figure out a solution. We're running the latest versions

WooCommerce 9.6.1
WooCommerce StripeGateway 9.1.1
WordPress 6.7.1

I'll report back here with our findings, we're looking into whether it's related to the IP address forwarding

**Comment by radicalwebs** [comment]
Same here on Kinsta, first time I've seen this error today.  Doesn't seem like there is anyway to verify the correct IP address in woocommerce or woopayments/stripe

**Comment by lynnjat7** [comment]
9405493-zen another case here with the latest Stripe:
WooCommerce - 9.6.1
Stripe - 9.1.1
WordPress - 6.7.2

**Comment by limist** [comment]
@lynnjat7 Thanks, on Kinsta too?

**Comment by lynnjat7** [comment]
Looks like WPEngine.

**Comment by feliciaoctocog** [comment]
Can confirm today we experienced this issue with a client's site on WpEngine with WordPress, Woocommerce, and Stripe updated. The payment failed 3 times with the same "Payment failed: Invalid IP address." error. After the customer tried the 4th time it succeeded.

One thing that I noticed that was interesting about this customer who tried to order 4 times was on the first 3 failed orders the Customer IP address was duplicated 3 times (ex: (104.29.32.125, 104.29.32.125, 104.29.32.125), but on the last successful order for the same customer there was only one IP address.

**Comment by lynnjat7** [comment]
Yes! What @feliciaoctocog said -> we also noticed that the customer IP address was duplicated 3x on the failed orders.

**Comment by amitramani** [comment]
Hello
I have been having the same exact issue. Here is my environment:
Wordpress: 6.7.2
Woocommerce : 9.6.2
Stripe: 9.1.1
Hosting: Kinsta

I am with Kinsta. I tried disabling CloudFlare on my site. It did not change anything. 

From reading this thread, I gather that resetting Stripe to "Legacy Mode" might resolve this issue. I am trying that now. 

If anyone has any other suggestions, please let me know. I can add some code and collect the needed logs to get this issue resolved. Look forward to hearing from you all.

**Comment by radicalwebs** [comment]
I managed to get payments to go through by disabling the Link Payments option in WooPayments - for anyone else using WooPayments (which goes through Stripe) I had installed Storefront and disabled all plugins but WooCommerce and WooPayments.

**Comment by amitramani** [comment]
@radicalwebs how do I disable Link Payments? I am not using WooPayments. 

I do remember turning on Link in some Stripe settings, just do not remember where it was. I can not find in the WooCommerce settings under Stripe.

**Comment by amitramani** [comment]
Sorry for the repeated replies, I was able to locate the setting for turning on/off Link in my Stripe Dashboard.

For reference, it is under your Stripe Dashboard->Settings->Payment Methods->Link

**Comment by radicalwebs** [comment]
> Sorry for the repeated replies, I was able to locate the setting for turning on/off Link in my Stripe Dashboard.
> 
> For reference, it is under your Stripe Dashboard->Settings->Payment Methods->Link

Did it work for you mate?

**Comment by annemirasol** [comment]
> I managed to get payments to go through by disabling the Link Payments

Yes, I believe this is a temporary workaround that should work, until we figure out which of the headers (`HTTP_X_REAL_IP`, `HTTP_X_FORWARDED_FOR`, or `REMOTE_ADDR`) has an unexpected format.

The workaround works because we call `WC_Geolocation::get_ip_address()` when building the mandate data that Stripe requires for certain payment methods. When the customer is using a credit card and Link is enabled, we also build the mandate. See https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8d95f3e613c235e6590dbabf3ab85cc388527bd6/includes/class-wc-stripe-intent-controller.php#L1028

I will work on:
- adding some logging on the header contents for when we get this failure
- see if we can skip the mandate data if the shopper is using a CC but not via Link.

**Comment by amitramani** [comment]
> > Sorry for the repeated replies, I was able to locate the setting for turning on/off Link in my Stripe Dashboard.
> > For reference, it is under your Stripe Dashboard->Settings->Payment Methods->Link
> 
> Did it work for you mate?

I just changed it recently. I am still receiving Failed Orders (with the same underlying IP address error). Will keep you posted. 

@annemirasol Can you give some guidance on how to add that code? I do have the Code Snippets plugin.

**Comment by annemirasol** [comment]
@amitramani Is it happening for all orders? If you check the wp-admin Edit Order page, what does the "Customer IP" say for the failing orders?

You can see that here:
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/f787253c-9f26-47bd-8907-731e3693310e" />

> Can you give some guidance on how to add that code? I do have the Code Snippets plugin.

Do you mean for logging the values for `HTTP_X_REAL_IP`, `HTTP_X_FORWARDED_FOR` and `REMOTE_ADDR`? Something like this in Code Snippets should work:

```
add_action( 'init', 'log_ip_issues' );
function log_ip_issues() {
    $logger = wc_get_logger();
    $log_filename = 'log-ip-issues';
    if ( ! class_exists( 'WC_Geolocation' ) ) {
        $logger->debug( 'WC_Geolocation does not exist!', [ 'source' => $log_filename ] );
        return;
    }
    $ip_address = WC_Geolocation::get_ip_address();
    if ( ! rest_is_ip_address( $ip_address ) ) {
        $log_data = "WC_Geolocation::get_ip_address(): $ip_address";
        if ( isset( $_SERVER['HTTP_X_REAL_IP'] ) ) {
            $log_data .= "\nHTTP_X_REAL_IP: " . sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_REAL_IP'] ) );
        }
        
        if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
            $log_data .= "\nHTTP_X_FORWARDED_FOR: " . sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_FORWARDED_FOR'] ) );
        }
        
        if ( isset( $_SERVER['REMOTE_ADDR'] ) ) {
            $log_data .= "\nREMOTE_ADDR: " . sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) );
        }
        $logger->debug( $log_data, [ 'source' => $log_filename ] );
    }
}	
```
The logs would be in WooCommerce > Status > Logs.

**Comment by amitramani** [comment]
> [@amitramani](https://github.com/amitramani) Is it happening for all orders? If you check the wp-admin Edit Order page, what does the "Customer IP" say for the failing orders?
It does not happen for all orders. Some orders go through successfully. I do not see the "Customer IP" listed for most of the Failed Orders. It just says "Payment via Credit / Debit Card" on that line where the "Customer IP" normally shows up. 
> 
> You can see that here: <img alt="Image" width="600" src="https://private-user-images.githubusercontent.com/730823/413407811-f787253c-9f26-47bd-8907-731e3693310e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk3NjU1NTUsIm5iZiI6MTczOTc2NTI1NSwicGF0aCI6Ii83MzA4MjMvNDEzNDA3ODExLWY3ODcyNTNjLTlmMjYtNDdiZC04OTA3LTczMWUzNjkzMzEwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxN1QwNDA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjIxMjcwNWM4NmNjODI3MWE2ODk4YmYxNjBkNzFkMzFjZmZkNGMzYjkxMDFiNWFkMzczZWFhNmJhMGYwNGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hSgS0bfU5TeBMTw5DWrmfDqGs3UvL93_ar5ttpHleFs">
> 
> > Can you give some guidance on how to add that code? I do have the Code Snippets plugin.
> 
> Do you mean for logging the values for `HTTP_X_REAL_IP`, `HTTP_X_FORWARDED_FOR` and `REMOTE_ADDR`? Something like this in Code Snippets should work:
> 
> ```
> add_action( 'init', 'log_ip_issues' );
> function log_ip_issues() {
>     $logger = wc_get_logger();
>     $log_filename = 'log-ip-issues';
>     if ( ! class_exists( 'WC_Geolocation' ) ) {
>         $logger->debug( 'WC_Geolocation does not exist!', [ 'source' => $log_filename ] );
>         return;
>     }
>     $ip_address = WC_Geolocation::get_ip_address();
>     if ( ! rest_is_ip_address( $ip_address ) ) {
>         $log_data = "WC_Geolocation::get_ip_address(): $ip_address";
>         if ( isset( $_SERVER['HTTP_X_REAL_IP'] ) ) {
>             $log_data .= "\nHTTP_X_REAL_IP: " . sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_REAL_IP'] ) );
>         }
>         
>         if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
>             $log_data .= "\nHTTP_X_FORWARDED_FOR: " . sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_FORWARDED_FOR'] ) );
>         }
>         
>         if ( isset( $_SERVER['REMOTE_ADDR'] ) ) {
>             $log_data .= "\nREMOTE_ADDR: " . sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) );
>         }
>         $logger->debug( $log_data, [ 'source' => $log_filename ] );
>     }
> }	
> ```
> 
> The logs would be in WooCommerce > Status > Logs.

OK, I will add that using Code Snippets and report back. 

I have noticed that the issue no longer happens. I am still not sure what Stripe settings cause this issue to occur. Whether it is having "Link" enabled as a payment method or the "Stripe Legacy Checkout" is disabled or a combination of the two. Hope to report back soon.

**Comment by feliciaoctocog** [comment]
Any updates on this issue? We've kept Stripe on the legacy checkout during this time, but the Pay Later options are not available for customers. My client wants to know if we can go back to the newest Stripe checkout experience and get off the Legacy Checkout experience.

**Comment by limist** [comment]
Bumping this thread, does anyone have further insights/fixes for this Invalid IP Number issue please?

**Comment by ChrisASearles** [comment]
Any updates on this? Also experiencing this with sites hosted on Kinsta. Would love to use some of the new options ASAP.

**Comment by amitramani** [comment]
I still get  Failed Orders but not as frequently as before. Earlier, every credit card order used to fail. Now, I get one here and there sporadically. Sorry, I know this is not of much help.

**Comment by OmarFPG** [comment]
9655467-zd-a8c

**Comment by annemirasol** [comment]
@ChrisASearles @amitramani 

We've added some logging in 9.3 which gets triggered when the system thinks the IP is invalid.

The log message would look like this:
<img width="800" alt="Image" src="https://github.com/user-attachments/assets/cba37963-feb0-4497-8e6f-b09a165641aa" />
\* Example from forcing the trigger, the IP above is valid.


Please search your logs for "Invalid IP address detected." and let us know the IP (format) that triggered it so we can ask WooCommerce core to add support for it.

**Comment by annemirasol** [comment]
@limist @feliciaoctocog Sorry, I missed tagging you in the message above ^

**Comment by annemirasol** [comment]
We have received a report that the IP address is in the format "\<ip-address\>, \<ip-address\>, \<ip-address\>", i.e. the same IP address repeated 3x, due to an unexpected `$_SERVER['REMOTE_ADDR']`. We believe this is due to some proxy/load balancer misconfiguration with the hosting provider. [REMOTE_ADDR should be a single IP address](https://datatracker.ietf.org/doc/html/rfc3875#section-4.1.8).

Hosting misconfiguration or not, I have filed a request for WooCommerce core to support this scenario, in https://github.com/woocommerce/woocommerce/issues/57249.

While waiting for WooCommerce core, one way to quickly move forward is to also add support in the plugin for this particular case, given we have more than a few merchants experiencing it.

**Comment by feliciaoctocog** [comment]
@annemirasol Thank you for including me in the update on the status of this issue. You had said in your comment above:

_"While waiting for WooCommerce core, one way to quickly move forward is to also add support in the plugin for this particular case, given we have more than a few merchants experiencing it."_

Where and what would I need to add to support the plugin in this specific case?

**Comment by annemirasol** [comment]
> to also add support in the plugin for this particular case, given we have more than a few merchants experiencing it.

@feliciaoctocog I am working on this.

**Comment by annemirasol** [comment]
UPDATE: I see @gigitux has a PR up in core already! https://github.com/woocommerce/woocommerce/pull/57284

UPDATE: https://github.com/woocommerce/woocommerce/pull/57284 has been merged. I expect the fix to land with the next WooCommerce release.

**Comment by annemirasol** [comment]
A Stripe-side patch has been released in 9.5.0 (released May 14, 2025), so we don't have to wait from WC 9.9
