### ISSUE TITLE
Auto check "Use a new payment method" on all cases

### ISSUE THREAD

**Issue by arunbasillal** [woocommerce/woocommerce-gateway-stripe#4141]
**Describe the bug**

When `Enable payments via saved cards` is enabled and the user has no saved cards, a checkbox that says `Use a new payment method` is displayed. If this checkbox is unchecked, the payment will fail. 

![Image](https://github.com/user-attachments/assets/0dfe70e1-5c4e-4e5c-90f6-a765c69cdbd8)

I am calling this a bug because it's causing potential lost revenue to users. 

**To Reproduce**

1. In Stripe settings for WooCommerce ([#](https://your-website.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings)), make sure `Enable payments via saved cards` is enabled. 

![Image](https://github.com/user-attachments/assets/cacc1133-ddca-4178-9019-83f546d1e2b6)

2. Make sure `Legacy checkout experience` is disabled.

3. In WooCommerce settings > `General Options` > `Default customer location`: Set it to `Geolocate`. You could also set it to a specific geo for testing purposes as well. 

![Image](https://github.com/user-attachments/assets/f9352f8f-9555-4bef-9546-63c202a703f0)

4. Add the code snippet below  to `functions.php` of your theme after modifying the default geo. In the code snippet below, I am using `IN` as the Geo to disable Stripe. Set that to your Geo (for USA, it's `US` I believe). The idea is that by default when the checkout page loads for the first time, Stripe will be disabled.

```
/**
 * Display payment gateways based on country. 
 * 
 * @link https://www.businessbloomer.com/disable-payment-gateway-specific-country-woocommerce/
 */
function payment_gateway_by_customer_location( $available_gateways ) {

	// Proceed only on WooCommerce checkout page.
	if ( ! is_checkout() ) {
		return $available_gateways;
	}

	if ( WC()->customer->get_billing_country() === 'IN' ) {

		if ( isset( $available_gateways['stripe'] ) ) {
			unset( $available_gateways['stripe'] );
		}
	}

	return $available_gateways;
}
add_filter( 'woocommerce_available_payment_gateways', 'payment_gateway_by_customer_location' );
```

5. Open the store on a private / incognito window as guest, proceed to checkout by adding a product. Stripe will be disabled by default.
6. Change Geo to a different country. Stripe will be visible now, hopefully with the radio button that reads `Use a new payment method` unchecked.
7. Refresh the page, and `Use a new payment method` radio button will be absent.

Adam was able to reproduce the issue and made a video here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4141#issuecomment-2769483442

**Expected behavior**

**Ideally, nothing should be displayed if no saved payment methods are available.** An easier fix would be check `Use a new payment method` as the default option so that it stays checked even when other saved payment methods not absent.

**Environment (please complete the following information):**

 - WordPress Version: 6.7.2
 - WooCommerce Version: 9.7.1
 - Stripe Plugin Version: 9.3.1
 - Browser [e.g. chrome, safari] and Version: Chrome
 - Any other plugins installed: Just WooCommerce and Stripe plugin. 

**Additional context**

This issue is discussed here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3142, and [here](https://wordpress.org/support/topic/woocommerce-stripe-gateway-use-a-new-payment-method/). The suggested solution is to disable `Enable payments via saved cards`. That works obviously, but that's disabling the feature altogether, not a fix.

**Comment by aheckler** [comment]
I cannot reproduce this issue, even when testing using a customer account with a saved card, and then disabling paying with saved cards (as admin of course).

Can you provide a complete set of steps to reproduce this on a brand new site with only WooCommerce and the Stripe gateway? Thanks!

**Comment by arunbasillal** [comment]
Hello @aheckler, thanks for taking a look.

> ... and then disabling paying with saved cards (as admin of course).

If paying with saved card is disabled, the radio button goes away. This was fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3142

The issue happens when you have the option enabled, but have no cards saved. In the screenshot above, I am trying to pay as a guest. 

Are we on the same page?

**Comment by aheckler** [comment]
Sorry for the confusion! We should be on the same page now.

That said, I still cannot replicate this on my site. I'm trying with the legacy checkout enabled and disabled, shortcode checkout and block checkout, various scenarios... no luck.

Can you send us a screenshot of the "WooCommerce Stripe Payment Gateway" section of the WooCommerce > Status page? Should look something like this:

![Image](https://github.com/user-attachments/assets/d2750a36-5037-4c23-83af-67e97faf63c9)

**Comment by aheckler** [comment]
Alternatively, if you can list a specific set of steps to reproduce this from scratch on a plain Woo site with nothing but our Stripe plugin installed, that would also work.

**Comment by arunbasillal** [comment]
Hello Adam,

Let me try recreating this on a fresh install and get back to you. 

To answer your questions. This happens with legacy checkout **disabled**, should have included that in the original steps to replicate. I have updated it now. 

Here are the exact steps I am using right now.

- `Enable payments via saved cards` is **checked** and `Enable the legacy checkout experience` is **unchecked**.
- Open the store in a new private tab > Add a product to cart and > Checkout. This is what I see:

![Image](https://github.com/user-attachments/assets/d93c3466-9d38-4b10-b481-74ff549185ac)

If I refresh the page, it goes away.

![Image](https://github.com/user-attachments/assets/57f263cf-302d-4f37-b410-f15f601f2566)

Tried it on Brave, Firefox and Edge to rule out a browser related issue. The fact that it goes away on refresh is a point of interest. Let me explore that. 

Status page screenshot as requested:

![Image](https://github.com/user-attachments/assets/733623d3-0aeb-440e-86a1-fd916dbfca58)

Once again, thank you for checking this out.

**Comment by aheckler** [comment]
I still cannot reproduce this. The closest I can get is, when my site is configured as you say, and I have no saved payment methods, I do see the checkbox _momentarily_ on the shortcode checkout page, until the form fully loads. Video:

https://github.com/user-attachments/assets/bc764ba7-dd51-46c5-b23e-5c59b4a8044b

I tried a couple different themes and browsers to see if that had something to do with it, but no luck there either. 

My gut says this is something particular to your site, so I'd be curious to see if you can replicate this on a blank/empty WP install.

**Comment by arunbasillal** [comment]
Hello again Adam,

I finally figured out the issue and you were right, it's something specific to my site, but it could still be improved, please hear me out. 

I had a code snippet that disables certain payment gateways based on Geo. I had Stripe disabled for India. Here is the one:

```
/**
 * Display payment gateways based on country. 
 * 
 * @link https://www.businessbloomer.com/disable-payment-gateway-specific-country-woocommerce/
 */
function payment_gateway_by_customer_location( $available_gateways ) {

	// Proceed only on WooCommerce checkout page.
	if ( ! is_checkout() ) {
		return $available_gateways;
	}

	if ( WC()->customer->get_billing_country() === 'IN' ) {

		if ( isset( $available_gateways['stripe'] ) ) {
			unset( $available_gateways['stripe'] );
		}
	}

	return $available_gateways;
}
add_filter( 'woocommerce_available_payment_gateways', 'payment_gateway_by_customer_location' );
```

Can you try these steps please? 

- In WooCommerce settings > `General Options` > `Default customer location`: Set it to `Geolocate`. You could also set it to a specific geo for testing purposes.

![Image](https://github.com/user-attachments/assets/86bf134c-5e45-4e96-b992-59897fd919ea)

- Add the code snippet above to `functions.php` of your theme after modifying the default geo. In the code snippet above, I am using `IN` as the Geo to disable Stripe. Set that to your Geo (for USA, it's `US` I believe). The idea is that by default when the checkout page loads for the first time, Stripe should be disabled. 
- Open the store on a private / incognito window as guest, proceed to checkout by adding a product.
- Stripe will be disabled by default. 
- Change Geo to a different country. Stripe will be visible now, hopefully with the radio button that reads `Use a new payment method` unchecked.
- Refresh the page, and `Use a new payment method` will be absent. 

Here is a recording I made - https://jmp.sh/2m1n2TfK (at 20 seconds, I refresh the page "off-camera").

Now I see that this is an edge case. However, couldn't this be fixed by checking `Use a new payment method` radio button by default? So that even if this happens, it has no consequence? 

Thanks again for your time.

**Comment by aheckler** [comment]
Ahh OK, I think I see the issue now. Video recording with narration:

https://github.com/user-attachments/assets/73f76ae1-447e-4325-99e0-634639e6626c

@Mayisha This does seem like a bug. The radio button should not even appear for logged out shoppers, right?

**Comment by arunbasillal** [comment]
Thanks for the confirmation Adam. I have updated the original post with the updated steps to reproduce the issue.

**Comment by Mayisha** [comment]
> @Mayisha This does seem like a bug. The radio button should not even appear for logged out shoppers, right?

Yes, that's correct. It should only appear for logged in users and when they have saved payment methods.

**Comment by annemirasol** [comment]
I am able to repro this issue only when `card` is the only payment method enabled in Stripe. This odd behavior is because WooCommerce's tokenization script does not get loaded, as [the Stripe code responsible for loading it](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/5f65d387aeb9086e8493f11dd5f6c5d4a667a2fa/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L787) does not get to run on page load (because no Stripe payment methods, i.e. gateways, are enabled).<br><br>The easiest workaround for this is to enable another Stripe payment method.

If that is not possible due to business decisions, you can use the filter `woocommerce_payment_gateway_get_new_payment_method_option_html` to check the radio button by default. See sample script below. You may want to add your conditions to control the situations where you want the radio button checked by default.

```
add_filter( 'woocommerce_payment_gateway_get_new_payment_method_option_html', 'auto_select_use_new_payment_method' );
function auto_select_use_new_payment_method( $html ) {
	$pattern = '/(type="radio")/';
  $replacement = '$1 checked="checked"';
  return preg_replace($pattern, $replacement, $html);
}
```

**Comment by annemirasol** [comment]
As there are workarounds for this issue, and there is not a lot we can do on the Stripe plugin side, I will be closing this issue. Feel free to re-open it, if we think it's worth another look.
