### ISSUE TITLE
PHP Notice:  Function _load_textdomain_just_in_time was called incorrectly [regression?]

### ISSUE THREAD

**Issue by georgeharito** [woocommerce/woocommerce-gateway-stripe#4210]
My `debug.log` is filled with these messages from the woocommerce-gateway-stripe plugin, a sample below:

`PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-gateway-stripe</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in <snip>/wp-includes/functions.php on line 6114`

I did a quick search in the discussions / issues tab of this plugin's Github and came across this commit that supposedly addresses the issue: 

https://github.com/woocommerce/woocommerce-gateway-stripe/commit/a4e0bf613bb34172356823e6c918d4c258fe36e3

The changelog in this commit states: 
> Fix - Prevents notices being displayed on WordPress 6.7 due to loading translations too early (only shown on stores with WP_DEBUG enabled).

I'm running the latest version of this plugin (v9.3.1), Wordpress 6.7.1 and Woocommerce 9.7.1 on PHP 8.2.

I concede it's not a very high priority issue, but when we turn on WP_DEBUG and the log is just filled with hundreds of these lines, it makes debugging an actual issue more difficult.

**Comment by daledupreez** [comment]
@Mayisha, is this a duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4085 and https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4140? Those issues were both fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4151.

**Comment by gabriel-fuentes** [comment]
@daledupreez 👋 - there is another case of this happening on 9602786-zen

**Comment by Mayisha** [comment]
That's correct @daledupreez 👍 

@georgeharito @gabriel-fuentes This has been fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4151. The fix will be shipped in the next release (version 9.4.0).

Closing it as fixed.

**Comment by ehclau** [comment]
@Mayisha I still see the following notices/warnings using 9.4.0-test-2:

Front end:
`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-gateway-stripe domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/html/wp-includes/functions.php on line 6121`

Admin:
`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-gateway-stripe domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/html/wp-includes/functions.php on line 6121 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6121) in /var/www/html/wp-includes/pluggable.php on line 1450 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6121) in /var/www/html/wp-includes/pluggable.php on line 1453`

I reprod using the following wp-env config without additional changes. Removing the stripe plugin will no longer present any notices or warnings. Not sure if the header information warning is directly related.
```
{
	"config": {
		"WP_DEBUG": true,
		"WP_DEBUG_DISPLAY": true,
		"SCRIPT_DEBUG": true,
		"WP_DEBUG_LOG": "/tmp/wp-errors.log",
		"FS_METHOD": "direct",
		"WP_ENVIRONMENT_TYPE": "local"
	},
	"core": null,
	"phpVersion": "8.3",
	"plugins": [
		"https://downloads.wordpress.org/plugin/woocommerce.9.8.1.zip",
		"./plugins/woocommerce-gateway-stripe"
	]
}
```

**Comment by Mayisha** [comment]
Thank you @malithsen for fixing the new occurrence in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4234

**Comment by chicharitomagnetico** [comment]
Still getting a lot of these on my log with version 9.4.1

**Comment by ehclau** [comment]
@chicharitomagnetico That's because 9.4.1 is a rollback of 9.4.0.

**Comment by dribgib** [comment]
Getting murdered in debug logs lol
