### ISSUE TITLE
Bug Report for WooCommerce Stripe Gateway Plugin

### ISSUE THREAD

**Issue by debugdubdubdub** [woocommerce/woocommerce-gateway-stripe#4595]
### Description

Issue Summary: When processing payments using the Stripe Payment Element, the checkout fails with the following JavaScript error:
```shell
Uncaught (in promise) IntegrationError: You specified "never" for fields.billing_details.address.state when creating the payment Element, but did not pass params.billing_details.address.state when calling stripe.createPaymentMethod(). If you opt out of collecting data via the payment Element using the fields option, the data must be passed in when calling stripe.createPaymentMethod().
``` 

### Steps to reproduce

We are using the multistep option and on the Payment part when the user clicks on Complete Order, it will show the error eventhough the state field is supplied by the user: "You specified "never" for fields.billing_details.address.state when creating the payment Element, but did not pass params.billing_details.address.state when calling stripe.createPaymentMethod(). If you opt out of collecting data via the payment Element using the fields option, the data must be passed in when calling stripe.createPaymentMethod()."

<details>

<summary>System report</summary>

`
### WordPress Environment ###

WordPress address (URL): https://skyspanshade.webignite.dev
Site address (URL): https://skyspanshade.webignite.dev
WC Version: 10.1.0
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: 6.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: ✔

### Server Environment ###

Server Info: nginx
Server Architecture: Linux 5.15.0-1081-gke x86_64
PHP Version: 8.2.29
PHP Post Max Size: 100 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.41-32
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 10.1.0
WC Database Prefix: wp_
Total Database Size: 47.60MB
Database Data Size: 35.38MB
Database Index Size: 12.22MB
wp_woocommerce_sessions: Data: 0.27MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.17MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_dlm_api_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_cookiemeta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_cookies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_downloads: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dlm_order_customer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dlm_order_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_order_transaction: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_reports_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_download_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jet_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.25MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 7.52MB + Index: 2.02MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.28MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sellkit_applied_alert: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sellkit_applied_coupon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sellkit_applied_discount: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sellkit_applied_funnel: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sellkit_contact_segmentation: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sellkit_funnel_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stripe_tax_for_wc_calculate_tax: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_stripe_tax_for_wc_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stripe_tax_for_wc_products: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stripe_tax_for_wc_tax_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stripe_tax_for_wc_tax_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.14MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfauditevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.44MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwafconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpr_above_the_fold: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_wpr_lazy_render_content: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wsal_metadata: Data: 1.52MB + Index: 3.97MB + Engine InnoDB
wp_wsal_occurrences: Data: 1.52MB + Index: 0.61MB + Engine InnoDB

### Post Type Counts ###

attachment: 791
custom_css: 2
dlm_download: 1
dlm_download_version: 1
elementor_library: 70
jet-engine: 1
jet-menu: 3
nav_menu_item: 67
oembed_cache: 16
page: 44
popup: 3
popup_theme: 8
post: 22
product: 3
product_variation: 112
revision: 1
rm_content_editor: 1
shop_coupon: 1
shop_order_placehold: 4
wc_pickup_location: 1
wp_navigation: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Advanced Custom Fields: by WP Engine – 6.5.0
Afterpay Gateway for WooCommerce: by Afterpay – 3.8.8
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.5
CookieYes | GDPR Cookie Consent: by CookieYes – 3.3.3
Download Monitor: by WPChill – 5.0.33
Duplicate Page: by mndpsingh287 – 4.5.5
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.21.1
Elementor Pro: by Elementor.com – 3.26.3
Elementor: by Elementor.com – 3.31.2
Gravity Forms: by Gravity Forms – 2.9.15
Gravity Forms Akismet Add-On: by Gravity Forms – 1.1.0
Gravity Forms reCAPTCHA Add-On: by Gravity Forms – 1.9.0
WPCode Lite: by WPCode – 2.3.0
JetElements For Elementor: by Crocoblock – 2.7.9.1
JetEngine: by Crocoblock – 3.7.3
JetMenu: by Crocoblock – 2.4.13
JetTabs For Elementor: by Crocoblock – 2.2.10
JetTricks: by Crocoblock – 1.5.6
Jupiter X Core: by Artbees – 4.9.2
Live Simple Clock: by Armel Tissi – 1.3
Meta pixel for WordPress: by Facebook – 4.1.5
Popup Maker: by Popup Maker – 1.20.6
LOCALiQ - Tracking Code: by ReachLocal
Inc. – 1.9.1

Redirection: by John Godley – 5.5.2
Saan World Clock: by andy kramer from saan.digital – 1.7
Sellkit Pro: by Artbees – 1.9.6
Sellkit: by Artbees – 2.3.5
Rank Math SEO: by Rank Math SEO – 1.0.251
Stripe Tax - Sales tax automation for WooCommerce: by  – 1.2.1
SVG Support: by  – 2.5.14
Swatchly - Variation Swatches for WooCommerce Products: by HasThemes – 1.4.5
User Role Editor: by Vladimir Garagulya – 4.64.5
Visibility Logic for Elementor: by StaxWP – 2.3.9
WooCommerce Cart Abandonment Recovery: by Brainstorm Force – 1.3.3
WooCommerce Stripe Gateway: by Stripe – 9.8.0
WooPayments: by WooCommerce – 9.8.0
WooCommerce Tax: by WooCommerce – 3.0.8
WooCommerce: by Automattic – 10.1.0
WP Activity Log: by Melapress – 5.4.2

### Inactive Plugins (6) ###

Autoptimize: by Frank Goossens (futtta) – 3.1.13
Classic Editor: by WordPress Contributors – 1.6.7
Menu Icons: by ThemeIsle – 0.13.18
WooCommerce Local Pickup Plus: by SkyVerge – 2.11.5 (update to version 2.11.7 is available)
Wordfence Security: by Wordfence – 8.0.5
WP Rocket: by WP Media – 3.17.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (6) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.3.0
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 6.5.1
WP Engine Update Source Selector: by WP Engine – 1.1.4

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
blueprint
point_of_sale
custom_order_tables

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 172 B

### WC Pages ###

Shop base: #2091 - /shop/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: #2093 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #2094 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: JupiterX Child
Version: 1.0.0
Author URL: https://jupiterx.com
Child Theme: ✔
Parent Theme Name: JupiterX
Parent Theme Version: 4.9.2
Parent Theme Author URL: https://artbees.net/
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: jupiterx/lib/templates/woocommerce/cart/cart.php version 7.9.0 is out of date. The core version is 10.1.0
jupiterx/lib/templates/woocommerce/checkout/thankyou.php
jupiterx/lib/templates/woocommerce/content-product.php
jupiterx/lib/templates/woocommerce/loop/rating.php
jupiterx/lib/templates/woocommerce/order/order-details-item.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/grouped.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/simple.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/variable.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
jupiterx/lib/templates/woocommerce/single-product/meta.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### WooPayments ###

Version: 9.8.0
Connected to WPCOM: Yes
WPCOM Blog ID: 240031124
Account ID: acct_1QXVEqFwEBQmV3Bt
Payment Gateway: Disabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Disabled
Documents: Enabled
Logging: Disabled

### WooCommerce Stripe Payment Gateway ###

Version: 9.8.0
Account ID: acct_1QgwvuBh5cpYOXXu
Account Email: accounts@skyspanshade.com.au
Test Mode Enabled: ✔
					No
OAuth Connected: ✔
					Yes
Sync Enabled: No
Legacy Checkout Experience: ✔
					No
Optimized Checkout Enabled: No
Enabled Payment Methods: card,link
Express Checkout: ✔
					Enabled (product,cart,checkout)
Auth and Capture: ✔
					Yes
Logging: ✔
					Yes

### Stripe ###

Account ID: Account ID could not be retrieved
please try to reconnect to Stripe.

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-mini-cart
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
experimental-wc-rest-api

Daily Cron: ✔ Next scheduled: 2025-08-16 22:50:29 +10:00
Options: ✔
Notes: 108
Onboarding: skipped

### Action Scheduler ###

Complete: 149
Oldest: 2025-07-17 23:51:59 +1000
Newest: 2025-08-17 00:15:26 +1000

Failed: 2
Oldest: 2025-08-16 01:54:37 +1000
Newest: 2025-08-16 22:48:03 +1000

Pending: 5
Oldest: 2025-08-17 01:13:29 +1000
Newest: 2025-08-22 06:25:54 +1000

### Status report information ###

Generated at: 2025-08-17 00:23:56 +10:00
`

</details>

**Comment by malithsen** [comment]
This is a duplicate of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2547. Issue was addressed in WooCommerce with https://github.com/woocommerce/woocommerce/issues/60096

**Comment by debugdubdubdub** [comment]
@malithsen I have the latest version of WooCommerce and WooCommerce Stripe Gateway Plugin but this does not resolve the issue im still having.

**Comment by malithsen** [comment]
@debugdubdubdub Although the issue has been fixed, it is not yet released. It is scheduled for release in the next WooCommerce version, 10.2.0.

**Comment by debugdubdubdub** [comment]
@malithsen is there a way we can get a quickfix we can apply to our website specially that this is very vital to our sales?

**Comment by malithsen** [comment]
@debugdubdubdub Since this issue is addressed on WooCommerce core, we don't have a lot of alternatives. One option is using the [10.2.0-beta.1](https://github.com/woocommerce/woocommerce/releases/tag/10.2.0-beta.1), but it comes with the risk of using a beta version that hasn't been fully vetted. Otherwise, the stable WooCommerce 10.2.0 is scheduled to be released on [Sept 16](https://developer.woocommerce.com/release-calendar/)

**Comment by debugdubdubdub** [comment]
Ok so i tried 10.2.0-beta.1, but unfortunately the issue still persists. Is there anything I need to do to confirm that the fix for this issue is on WooCommerce 10.2.0? or is this a different issue?

**Comment by debugdubdubdub** [comment]
latest system report attached.

[SystemStatusReport_skyspanshade.webignite.dev_2025-09-04T16-16-08.txt](https://github.com/user-attachments/files/22142764/SystemStatusReport_skyspanshade.webignite.dev_2025-09-04T16-16-08.txt)

**Comment by annemirasol** [comment]
> We are using the multistep option

@debugdubdubdub What do you mean by this? I tried looking for a "multistep checkout" plugin in your system report, but found none. Could you send us a video, or screenshots of what is happening? Thank you!

**Comment by debugdubdubdub** [comment]
> > We are using the multistep option
> 
> [@debugdubdubdub](https://github.com/debugdubdubdub) What do you mean by this? I tried looking for a "multistep checkout" plugin in your system report, but found none. Could you send us a video, or screenshots of what is happening? Thank you!

I just meant multistep as going through these pages Cart > Information > Shipping > Payment

<img width="1202" height="1153" alt="Image" src="https://github.com/user-attachments/assets/ba02862a-f6b7-4d2b-a1a2-38eeaeb0397a" />

**Comment by annemirasol** [comment]
@debugdubdubdub Are you doing multi-step via your JupiterX theme?

Can you try this: on the payment step, open your browser console and enter `document.querySelector( '#billing_state' )?.value`. Do you get an `undefined`?

I believe this is happening because the Stripe plugin assumes it has access to the WooCommerce checkout form when the shopper submits the order.

**Comment by wjrosa** [comment]
Hi @debugdubdubdub ! I'm just ping you again in case you missed Anne's message above. Could you please try that and let us know?

**Comment by Mayisha** [comment]
Hi @debugdubdubdub 
I am closing this issue for now as we have not heard back from you. Please feel free to reopen the issue with the requested details if you are still getting the error.
