### ISSUE TITLE
BUG: Broken "Pay for Order" Checkout with v4.0.2 (WP v4.9.2, WC v3.2.6) 

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/woocommerce-gateway-stripe#463]
#### Steps to reproduce the issue

WooCommerce Stripe Gateway v4.0.2
WP v4.9.2,
WC v3.2.6
WC > PayPal Standard & Stripe gateways enabled
 
Create a manual order, then from the Edit Order page click on "Customer payment page →". Try to checkout there with PayPal, and it won't work. Checkout keeps spinning and won't send the customer to PayPal.

If you inspect element, you get 5 JS errors from Stripe.min.js: https://www.screencast.com/t/MysjdFGlDF

Please help!!!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Just tested this. No issues here. I am redirected to PayPal. Can you please pull down the master branch and test that? Disregard what the version says.

**Comment by BusinessBloomer** [comment]
Thanks Ray for your super prompt reply. I just did download the master branch for Stripe, and I still get the error I'm afraid.

I switched on only 2016 theme, Woo 3.2.6 and Stripe 4.0.2

**Comment by roykho** [comment]
@BusinessBloomer ok I have pushed up some changes that may fix your issue. Can you please give that a go?

**Comment by BusinessBloomer** [comment]
Thanks so much - but I'm afraid I still get the 4 JS errors (not sure if that's the reason the checkout spins):

Your card number is incomplete.
js.stripe.com/:1 Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLDocument.onError (stripe.min.js?ver=4.0.2:1)
    at HTMLDocument.dispatch (jquery.js:3)
    at HTMLDocument.r.handle (jquery.js:3)
    at Object.trigger (jquery.js:3)
    at Object.a.event.trigger (jquery-migrate.min.js:2)
    at HTMLBodyElement.<anonymous> (jquery.js:3)
    at Function.each (jquery.js:2)
    at a.fn.init.each (jquery.js:2)
    at a.fn.init.trigger (jquery.js:3)
    at stripe.min.js?ver=4.0.2:1
stripe.min.js?ver=4.0.2:1 Your card's expiration date is incomplete.
js.stripe.com/:1 Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLDocument.onError (stripe.min.js?ver=4.0.2:1)
    at HTMLDocument.dispatch (jquery.js:3)
    at HTMLDocument.r.handle (jquery.js:3)
    at Object.trigger (jquery.js:3)
    at Object.a.event.trigger (jquery-migrate.min.js:2)
    at HTMLBodyElement.<anonymous> (jquery.js:3)
    at Function.each (jquery.js:2)
    at a.fn.init.each (jquery.js:2)
    at a.fn.init.trigger (jquery.js:3)
    at stripe.min.js?ver=4.0.2:1
stripe.min.js?ver=4.0.2:1 Your card's security code is incomplete.
js.stripe.com/:1 Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLDocument.onError (stripe.min.js?ver=4.0.2:1)
    at HTMLDocument.dispatch (jquery.js:3)
    at HTMLDocument.r.handle (jquery.js:3)
    at Object.trigger (jquery.js:3)
    at Object.a.event.trigger (jquery-migrate.min.js:2)
    at HTMLBodyElement.<anonymous> (jquery.js:3)
    at Function.each (jquery.js:2)
    at a.fn.init.each (jquery.js:2)
    at a.fn.init.trigger (jquery.js:3)
    at stripe.min.js?ver=4.0.2:1
stripe.min.js?ver=4.0.2:1 Your card number is incomplete.
stripe.min.js?ver=4.0.2:1 Uncaught (in promise) TypeError: Cannot read property 'top' of undefined
    at HTMLDocument.onError (stripe.min.js?ver=4.0.2:1)
    at HTMLDocument.dispatch (jquery.js:3)
    at HTMLDocument.r.handle (jquery.js:3)
    at Object.trigger (jquery.js:3)
    at Object.a.event.trigger (jquery-migrate.min.js:2)
    at HTMLBodyElement.<anonymous> (jquery.js:3)
    at Function.each (jquery.js:2)
    at a.fn.init.each (jquery.js:2)
    at a.fn.init.trigger (jquery.js:3)
    at sourceResponse (stripe.min.js?ver=4.0.2:1)

**Comment by roykho** [comment]
That is strange. I am not getting those errors. Are you certain, you clear your browser cache and refreshed the browser?

**Comment by BusinessBloomer** [comment]
Yep :)

I'm going to DM you the link to the payment page, so you can test :)

**Comment by BusinessBloomer** [comment]
Uhm I can't DM you. The link is https://staging8.businessbloomer.com/checkout/order-pay/73467/?pay_for_order=true&key=wc_order_5a5f999662815

**Comment by BusinessBloomer** [comment]
And not even bank transfer works :)

**Comment by roykho** [comment]
Ah ok my setup is different hence I couldn't reproduce it. On mine I have saved cards. So if the saved cards is selected, this issue doesn't happen ![](http://cld.wthms.co/uz2xMK+)

I will look into this.

**Comment by BusinessBloomer** [comment]
Excellent, thank you so much Roy (not Ray lol)

**Comment by roykho** [comment]
Ok please give master branch a go.

**Comment by BusinessBloomer** [comment]
Looks good to me Roy! Thank you :)
