### ISSUE TITLE
Shipping cost not added with Apple Pay

### ISSUE THREAD

**Issue by kentaroyamada** [woocommerce/woocommerce-gateway-stripe#537]
#### What I expected

Shipping cost to be added to the final Apple Pay check out price to be paid by the customer 

#### What happened instead

Shipping cost is not added even though it is in the dialogue box (METHOD)
If I go to normal Strip check out, shipping is added accordingly.

#### Steps to reproduce the issue

https://neandertal.co.uk/shop/dark-sample/

I am using 
WC 2.6.9  
I installed latest 3.3.1 but the Apple Pay button disappeared from simple product page so I rolled back to this version. (This is suspicious? - is this a known bug?)
WP version:4.9.4 

I am using Cloudflare and Full SSL setting there. My server hosts a certificate/key.

![screen shot 2018-02-13 at 22 19 58](https://user-images.githubusercontent.com/1729974/36178524-0415a616-1111-11e8-84f8-30de6b54f565.png)

I just realised shipping is not added at all in Chrome

![screen shot 2018-02-13 at 22 42 29](https://user-images.githubusercontent.com/1729974/36178529-08ad4404-1111-11e8-9a83-67c44de9a133.png)

![screen shot 2018-02-13 at 22 31 48](https://user-images.githubusercontent.com/1729974/36178544-1beba7cc-1111-11e8-86b6-655f2a7ad329.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please provide more information. What version Stripe are you using? In your Apple Pay Wallet and Chrome, do you have more than one mailing address? What if you specifically clicked on the address after the popup to select the address even if there is only one?

**Comment by kentaroyamada** [comment]
I am using  WooCommerce Stripe Gateway |   | by WooCommerce – 4.0.5

Yes I have couple of addresses in Apply Pay / Chrome, but even if I select the address, it doesn't add the shown shipping cost according to the address.
It's £3 shipping for UK (for me). I can see the cost inside Apple Pay (Chrome) dialogie box but it is not added to the final cost

Thank you.

**Comment by kentaroyamada** [comment]
@roykho Thank you very much for your reply.
Perhaps the best thing is to have a look on live site https://neandertal.co.uk/shop/dark-sample/

I am also wondering if I should update WC to latest.. but when I updated to the latest few days ago, Apple Pay stopped working so I am a bit scared..

Thank you!

**Comment by roykho** [comment]
@kentaroyamada do you have a staging site where you can setup WC latest version?

**Comment by kentaroyamada** [comment]
@roykho Hi Roy,
I have just installed the latest WC in here
https://staging.neandertal.co.uk/shop/dark-sample/
Now Apple Pay / Chrome Pay stopped working.. :(
Kentaro

**Comment by roykho** [comment]
@kentaroyamada right thats because your site is seeing a "403" error in the JS console. And I see some debugging messages "zero". I am not sure what that means. Do you perhaps have conflicting plugins installed?

**Comment by kentaroyamada** [comment]
@roykho Thank you very much for your quick response.
Yes I have deleted the js script which was out putting the debugging message 'zero' and I fixed the 404 js code which related to Google Map.  It seems there is no console errors.
But still Apple Pay button is not showing up!  I wonder why..?

**Comment by roykho** [comment]
@kentaroyamada I am still seeing that error ![](http://cld.wthms.co/Wwcpa9+) and also are you sure you have set the domain registration to your staging site?

**Comment by kentaroyamada** [comment]
@roykho 
Hi Roy thank you very much for being patient.

Yes this staging site was was working with stripe Apple Pay and Chrome Pay until I updated the WC to latest about an hour ago.

It appears this 403 message doesn't always occur to me. 
It happens in rare instance. I can't replicate any more but 403 only showed up when I added a product to the basket previously..

Bridge theme is installed and version is 7.6.2

Currently there is no 403 or other errors

![screen shot 2018-02-15 at 17 15 07](https://user-images.githubusercontent.com/1729974/36270530-d04199c6-1273-11e8-98da-b086f438c9e1.png)

**Comment by roykho** [comment]
Perhaps in WC 3.3, your theme is not compatible? Have you tried a WP default theme?

**Comment by kentaroyamada** [comment]
@roykho Thanks again you for your help Roy!

I tried default WP theme and it seemed working with Chrome (but not fully with Safari/Apple Pay)
therefore I decided to update Bridge theme to the latest version. 

And yes! Chrome Pay is working fine now! But Apply Pay is not working. 
Now it has 400 Error. 
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (sessions, line 0)

Maybe we are getting close?

![screen shot 2018-02-15 at 23 33 19](https://user-images.githubusercontent.com/1729974/36286814-45c74fa8-12a9-11e8-93f6-da6b50d46ff7.png)

**Comment by roykho** [comment]
Not sure what you mean by "not fully"? Can you switch to default again so I can see?

**Comment by kentaroyamada** [comment]
@roykho Sure. I have changed the theme to Twenty Fifteen
https://staging.neandertal.co.uk/shop/dark-sample/

**Comment by roykho** [comment]
Change the product price to be at least 1 dollar.

**Comment by kentaroyamada** [comment]
@roykho yes I have changed to 1.00

**Comment by roykho** [comment]
This is the error I see `Before you can start using Apple Pay on the Web, you need to first register your domain. For more information`

**Comment by kentaroyamada** [comment]
Yes I was trouble shooting this 400 Error. staging.neandertal.co.uk was definitely registered with curl command.. Then when I changed to Test Mode it stared working..

I updated live site's theme to latest and WC to latest and now it is working.. 

It was probably caused by API private/public keys used by same domain, one with subdomain and one without..?

Thank you very much for all of your help. Best

**Comment by adez2018** [comment]
Hello, i am having the same problem on my website TeeZeeWatches.com did you find out the resolution for this? 

When i use Apple Pay my shipping says "Flat Rate $5.95" but it does not show up in the sub total and the customer is not paying shipping. Please help!

I am using Woo Commerce, Stripe Integration, everything is up to date. I contacted Apple & Stripe they seem to think it is a woo commerce issue?

**Comment by topraf** [comment]
@adez2018 Hey, did you find a solution? I'm having the same issue

**Comment by LavishRawat** [comment]
@adez2018 @topraf  I'm facing the same issue. Did you find any fix?
